config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "seasons#index"

  get 'articles/:id', to: 'articles#show', as: :article
  get 'issues/:id', to: 'issues#show', as: :issue
  get 'magazines/:id/stylesheet', to: 'magazines#stylesheet', as: :magazine_stylesheet
  get 'magazines/:id', to: 'magazines#show', as: :magazine
  get 'seasons', to: 'seasons#index', as: :seasons

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :issue
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :articles
  belongs_to :magazine
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  has_many :issues
  belongs_to :season
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :magazines

  def title
    return "#{year}/#{year+1}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
    @magazine = @article.issue.magazine
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
    @issue = Issue.find(params[:id])
    @magazine = @issue.magazine
  end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController

  def show
    @magazine = Magazine.find(params[:id])
  end

  def stylesheet
    @magazine = Magazine.find(params[:id])

    respond_to do |format|
      format.html { render :text => @magazine.style, :content_type => "text/css" }
      format.css { render :text => @magazine.style, :content_type => "text/css" }
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true,
      no_intraemphasis: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/articles/show.html.erb
<div class="container article">
  <%= link_to '<-' + @article.issue.title, issue_path(@article.issue) %>

  <h1><%= @article.title %></h1>

  <%= markdown(@article.content) %>

  <h2>Comments, likes, shares</h2>
</div>

app/views/issues/show.html.erb
<div class="container issue">
  <%= link_to '<-' + @issue.magazine.title, magazine_path(@issue.magazine), :class => "back" %>

  <h1 class="title"><%= @issue.title %></h1>

  <% @issue.articles.each do |article| -%>
    <div class="article">
      <h2><%= link_to article.title, article_path(article) %></h2>

      <div class="content">
        <%= markdown(article.content) %>
      </div>
    </div>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oligraphy</title>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <% if @magazine %>
      <link href="<%= magazine_stylesheet_path(@magazine) %>" rel="stylesheet" type="text/css" />
    <% end %>

    <div class="top">
      <%= link_to "Oligrafija", root_path %>
    </div>
    <% flash.each do |name, msg| -%>
      <%= msg %>
    <% end -%>

    <%= yield %>

    <% if Rails.env.development? %>
      <!-- <div class="alert alert-info alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= debug(params)%>
      </div> -->
    <% end %>
  </body>
</html>

app/views/magazines/show.html.erb
<div class="container magazine">
  <h1 class="title"><%= @magazine.title %></h1>

  <% @magazine.issues.each do |issue| -%>
    <div class="row issue">
      <div class="col-lg-6 cover">

        <%= link_to issue_path(issue) do %>
          <%= image_tag("covers/angliukas-issue.png", :class => "background") %>
          <div class="details">
            <h4 class="title"><%= issue.title %></h4>
          </div>
        <% end %>

      </div>


      
      <div class="col-lg-6 index">
        <ol>
          <% issue.articles.each do |article| %>
            <li><%= link_to article.title, article_path(article) %></li>
          <% end %>
        </ol>

      </div>
    </div>
  <% end -%>
</div>

app/views/seasons/index.html.erb
<% @seasons.each do |season| %>
  <div class="season">
    <div class="header">
      <h3><span class="minor"><%= "#{season.year}/" %></span><%= "#{season.year + 1}" %></h3>
    </div>

    <div class="container">
      <div class="row">
        <% season.magazines.each do |magazine| %>
          <div class="magazine col-lg-4">
            <%= link_to magazine_path(magazine) do %>
              <%= image_tag("covers/angliukas.png", :class => "background") %>
              <div class="details">
                <h4 class="title"><%= magazine.title %></h4>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>